# Generated by Django 2.0 on 2018-02-14 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0002_auto_20180214_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('abbrev', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('division', models.CharField(choices=[('atl', 'Atlantic'), ('cen', 'Central'), ('met', 'Metropolitan'), ('pac', 'Pacific'), ('sou', 'Southeast')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countries.Country')),
            ],
        ),
    ]
