#!/usr/bin/env bash

cat <<END
nhlcom_id: 

country_abbrev: 
team_abbrev: 

first_name: 
last_name: 
number: 
born: yyyy-mm-dd

potential: 

salary: 
years_left: 

height: 
weight: 
position: 
type: 
shoots: 

draft_team_abbrev: 
draft_year: 
draft_round: 
draft_overall: 

overall: 

puck_skills: 
senses: 
shooting: 
defense: 
skating: 
physical: 

deking: 
hand_eye: 
passing: 
puck_control: 

discipline: 
offensive_awareness: 
poise: 

slap_shot_accuracy: 
slap_shot_power: 
wrist_shot_accuracy: 
wrist_shot_power: 

defensive_awareness: 
faceoffs: 
shot_blocking: 
stick_checking: 

acceleration: 
agility: 
balance: 
endurance: 
speed: 

aggressiveness: 
body_checking: 
durability: 
fighting_skill: 
strength: 
END
