# Generated by Django 2.0 on 2018-02-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skater',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_skaters', to='countries.Country'),
        ),
        migrations.AlterField(
            model_name='skater',
            name='draft_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players_skaters_drafted', to='teams.Team'),
        ),
        migrations.AlterField(
            model_name='skater',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players_skaters', to='teams.Team'),
        ),
    ]
